[package]
name = "csvtxs"
version = "0.1.0"
authors = ["Andrew Jones <ascjones@gmail.com>"]

[dependencies]
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
csv = "1.0.0-beta.4"
chrono = "0.4.0"
currency = "0.4.0"
regex = "0.2"